/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 **************************************** **************************************
 ****************************************
 ****************************************
 Port: A
 Pin: 5
 */

#include <stdint.h>

#define PERIPH_BASE 		(0x40000000UL)
#define AHB2_OFFSET 		(0x008000000UL )
#define AHB2_PERIPH_BASE 	( PERIPH_BASE + AHB2_OFFSET )
#define GPIOA_OFFSET 		(0x00u)
#define GPIOA_BASE 			( AHB2_PERIPH_BASE + GPIOA_OFFSET )

#define AHB1_PERIPH_BASE	( 0x40020000UL )
#define RCC_OFFSET 			( 0x00001000UL )
#define RCC_BASE 			( AHB1_PERIPH_BASE + RCC_OFFSET )



#define GPIOAEN 			( 1u << 0 )
#define PIN5 				( 1U << 5 )
#define LED_PIN				PIN5

#define __IO volatile

typedef struct{
	__IO uint32_t padding[ 19 ];
	__IO uint32_t AHB2ENR;     /*!< RCC AHB2 peripheral clocks enable register,                              Address offset: 0x4C */
}RCCTypeDef;




typedef struct{
	__IO uint32_t MODER;
	__IO uint32_t OTYPER;
	__IO uint32_t OSPEEDR;
	__IO uint32_t PUPDR;
	__IO uint32_t IDR;
	__IO uint32_t ODR;
	__IO uint32_t BSRR;
	__IO uint32_t LCKR;
	__IO uint32_t AFR[ 2 ];
}GPIOTypeDef;


#define RCC 	( ( RCCTypeDef* ) RCC_BASE )
#define GPIOA	( ( GPIOTypeDef* ) GPIOA_BASE )

static void toggle_PA5(){
//	GPIOA_OD_R ^= LED_PIN;
	GPIOA->ODR ^= LED_PIN;
}

/*
 * |= ( 1 << 10 ) set bit 10 to 1
 * &= ~( 1 << 11 ) set bit 11 to 0
 */
int main( void ){
	// 1. enable clock access to GPIOA
//	RCC_AHB2EN_R |= GPIOAEN;
 	RCC->AHB2ENR |= GPIOAEN;
	// 2. set PA5 as output pin
//	GPIOA_MODE_R |= ( 1 << 10 );
//	GPIOA_MODE_R &= ~( 1 << 11 );
	GPIOA->MODER |= ( 1 << 10 );
	GPIOA->MODER &= ~( 1 << 11 );

	while( 1 ){
		// 3 set PA5 pin
		toggle_PA5();
		for( int i = 0; i < 70000; i ++ );

	}

	return 0;
}
